name: 'Trivy Security Scan'
description: 'Run Trivy vulnerability scanning with configurable options'

inputs:
  subproject:
    description: 'For gradle multi module projects, leave blank for single module projects'
    required: false
    default: ''
  severity:
    description: 'Customisable severity levels'
    required: false
    default: 'HIGH,CRITICAL'
  scan_type:
    description: 'A scan type to use - either image (default) or fs'
    required: false
    default: 'image'
  scanners:
    description: 'A comma-separated list of scanners to use to scan'
    required: false
    default: 'misconfig,vuln,secret'
  location:
    description: 'A location for IaC scans to take place'
    required: false
    default: '.'
  ignore_unfixed:
    description: 'Ignore vulnerabilities that have no current fix'
    required: false
    default: 'true'
  limit_severities_for_sarif:
    description: 'only includes severities as defined in the sarif file'
    required: false
    default: 'true'
  github_token:
    description: 'GitHub token for authentication'
    required: false
    default: ''
  ECR_REGION:
    description: 'The AWS region that the ECR repository was created in'
    required: false
    default: 'eu-west-2'
  ECR_ROLE_TO_ASSUME:
    description: The AWS role to assume to authenticate to ECR
    required: false
  ECR_REGISTRY_URL:
    description: The URL of the ECR registry
    required: false

outputs:
  results_count:
    description: 'Number of vulnerabilities found'
    value: ${{ steps.trivy-summary.outputs.results_count }}
  summary:
    description: 'Formatted summary of vulnerabilities'
    value: ${{ steps.trivy-summary.outputs.summary }}
  sarif_upload_outcome:
    description: 'Outcome of the SARIF upload step'
    value: ${{ steps.trivy-upload.outcome }}

runs:
  using: composite
  steps:
  - name: Trivy disabled
    run: echo "Trivy has temporarily been disabled"
    shell: bash