version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of workflow files
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "ministryofjustice/hmpps-github-actions"
        versions: [">=2"] # WORKFLOW_VERSION
