name: Backup Repository to SharePoint

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '55 1 * * *'

permissions:
  contents: read

jobs:
  backup:
    name: Backup to SharePoint
    runs-on: ubuntu-latest
    env:
      SP_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
      SP_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      AZ_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false
      - name: Backup repository to SharePoint
        uses: ./.github/actions/sharepoint_repository_backup
        with:
          retention_count: 5 # optional, defaults to 5
